const MONGODB_URL = exports.MONGODB_URL = process.env.MONGODB_URL;
const AZURE_DASHBOARD_BASE_URL = exports.AZURE_DASHBOARD_BASE_URL = process.env.AZURE_DASHBOARD_BASE_URL;
const AZURE_DASHBOARD_TOKEN = exports.AZURE_DASHBOARD_TOKEN = process.env.AZURE_DASHBOARD_TOKEN;